

server {
	server_name 42.fr
	listen 80 8080
	index index.html
	root /
	methods GET POST
#	location / {
#		methods GET POST DELETE
#		autoindex off
#	}
#	location /hheghine {
#		redirect https://github.com/hheghine
#	}
}

# autoindex is a directive that controls directory listing.
# When autoindex is set to on, the server will automatically
# generate and display a list of files in a directory if no
# index file (e.g., index.html) is found. This is useful for
# directories that don't have an index file and you want to
# show the files within them to users accessing that directory
# via a web browser.

# On the other hand, when autoindex is set to off,
# the server will not generate a directory listing,
# and if no index file is found, it will typically
# return a "403 Forbidden" error or a similar response
# indicating that directory listing is not allowed.