

server {
	server_name 42.fr
	listen 127.0.0.1:11223
	listen 42
	index index.html
	root /
	autoindex off
	methods GET POST
	location / {
		methods GET POST DELETE
		autoindex off
	}
	location /hheghine {
		redirect https://github.com/hheghine
	}
}

server {
    listen 7070
    server_name localhost

    location / {
        index index.html
    }
}

# Custom Error Pages: Serve custom error pages for specific HTTP status codes.
# location / {
#     error_page 404 /404.html;
#     error_page 500 502 503 504 /50x.html;
# }

# Logging: Customize logging for the location.
# location / {
#     access_log /var/log/nginx/access.log main;
#     error_log /var/log/nginx/error.log warn;
# }

# autoindex is a directive that controls directory listing.
# When autoindex is set to on, the server will automatically
# generate and display a list of files in a directory if no
# index file (e.g., index.html) is found. This is useful for
# directories that don't have an index file and you want to
# show the files within them to users accessing that directory
# via a web browser.

# On the other hand, when autoindex is set to off,
# the server will not generate a directory listing,
# and if no index file is found, it will typically
# return a "403 Forbidden" error or a similar response
# indicating that directory listing is not allowed.